name: 🧩 개발 작업 템플릿
description: 개발 작업 또는 기능 추가를 위한 이슈 템플릿
title: "[파트][목적] 작업 요약 "
labels: []
body:
  - type: textarea
    id: work
    attributes:
      label: "## 작업 내용"
      description: "구현할 주요 기능, 수정 사항 등을 자세히 적어주세요."
      placeholder: |
        - 레벨 10 도달 시 서버에서 보스 1회 생성
        - GameState에 Phase 반영
        - HUD에 보스 등장 신호 송출
    validations:
      required: true

  - type: textarea
    id: files
    attributes:
      label: "## 변경 파일"
      description: "수정된 파일 목록을 작성해주세요."
      placeholder: |
        - MainGameMode.h / .cpp
        - MainGameState.h / .cpp
    validations:
      required: true

  - type: textarea
    id: test
    attributes:
      label: "## 테스트 방법"
      description: "기능 확인을 위해 어떤 테스트를 해야 하는지 작성해주세요."
      placeholder: |
        - 레벨 9: 보스 생성 X
        - 레벨 10: 보스 1회 생성
        - 이후 중복 생성 없음
    validations:
      required: false

  - type: textarea
    id: considerations
    attributes:
      label: "## 고려 사항"
      description: "특이사항, 후속 작업(PR), 주의점 등을 작성해주세요."
      placeholder: |
        - GameMode만 수정 (UI는 별도 PR 예정)
    validations:
      required: false
